INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10001, 'Sudeshna', 'Learn Google Cloud', CURRENT_DATE(), FALSE);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10002, 'Sudeshna', 'Learn Spring Boot', CURRENT_DATE(), FALSE);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10003, 'Sudeshna', 'Learn React', CURRENT_DATE(), FALSE);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10004, 'Sudeshna', 'Learn Docker', CURRENT_DATE(), FALSE);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10005, 'Sudeshna', 'Learn Kubernetes', CURRENT_DATE(), FALSE);