package com.in28minutes.rest.webservices.hello_world_java;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class RestfulWebServicesApplication {

	public static void main(String[] args) {
		SpringApplication.run(RestfulWebServicesApplication.class, args);
	}

}

//use mvn spring-boot:build-image to automatically build the docker image
//OCI ~ Open Container Initiative compatible image is generated by this command
//OCI image can be run on any OCI-compliant container runtime, such as Docker or Kubernetes.
//This image is smaller and the build process is optimized for Java applications compared to traditional Docker images.
//Most Spring boot projects use build-image command to create OCI images for deployment in containerized environments.

